### ISSUE TITLE
OAuth on Api Platform swagger is not configured

### ISSUE THREAD

**Issue by loic425** [Monofony/Monofony#246]
**Monofony version affected**: 0.4

**Description**  
OAuth on Api Platform swagger is not configured.

**Steps to reproduce**  
http://localhost:8000/api

**Possible Solution** 
```
# config/packages/monofony_api.yaml
api_platform
    swagger:
        [..]
        api_keys:
            apiKey:
                name: Authorization
                type: header

```
